# This workflow will build and test a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/swift.yml'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/swift.yml'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        swift: ["5.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: kennethlaskoski/setup-swift@main
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
